version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${env:DB_HOST}
            port: '5432'
            database: ${env:DB_DATABASE}
            ssl: true
            user: ${env:DB_USER}
            password: ${env:DB_PASSWORD}
            migrations: true
